language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https python-docutils rubygems
  - git clone https://github.com/varnish/Varnish-Cache.git ./varnish
  - cd varnish
  - ./autogen.sh
  - ./configure
  - make
  - sudo make PREFIX="/usr/local" install
  - cd ..
  - wget http://download.redis.io/releases/redis-3.0.7.tar.gz
  - tar zxvf redis-*.tar.gz
  - cd redis-*
  - make
  - sudo make PREFIX="/usr/local" install
  - sudo ldconfig
  - sudo cp src/redis-trib.rb /usr/local/bin
  - cd ..
  - wget --no-check-certificate https://github.com/redis/hiredis/archive/v0.13.3.zip -O hiredis-0.13.3.zip
  - unzip hiredis-*.zip
  - cd hiredis-*
  - make
  - sudo make PREFIX="/usr/local" install
  - sudo ldconfig
  - cd ..
  - gem install redis

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j1

script:
  - make check -j1

compiler:
  - clang
  - gcc
